name: Auto Commit

on:
  schedule:
    - cron: '2 * * * *'  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@main
      run:
        git clone https://${{ secrets.API_GITHUB_TOKEN }}@github.com/putri577/putri577.git

    - name: Make changes
      run: 
        cd putri577
        date "+%Y-%m-%d %H:%M:%S" >> data.txt

    - name: Commit and push if it changed
      run: |
        cd putri577
        git config --local user.email "RonggolawePutri577@gmail.com"
        git config --local user.name "Putri577"
        git add .
        git commit -m 'update today date'
        git push origin main
