name: Auto Commit

on:
  schedule:
    - cron: '45 * * * *'  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@main

    - name: Fetch data
      run: |
        # Replace this with the command you use to fetch data
        date "+%Y-%m-%d %H:%M:%S" >> data.txt

    - name: Commit and push if it changed
      uses: github-actions-x/commit@v2.9
      with:
        push-branch: 'main'
        email: RonggolawePutri577@gmail.com
        name: Putri577
        commit-message: 'Updated data'
        force-add: 'true'
        force-push: 'true'
