name: Auto Commit

on:
  schedule:
    - cron: '2 * * * *'  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@main
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }} 

    - name: Make changes
      run: |
        date "+%Y-%m-%d %H:%M:%S" >> data.txt

    - name: Commit and push if it changed
      run: |
        git config --global user.email "RonggolawePutri577@gmail.com"
        git config --global user.name "Putri577"
        git add -A
        git diff --quiet && git diff --staged --quiet || (git commit -m 'Automated commit'; git push)
