name: Auto Commit

on:
  schedule:
    - cron: '20 5 * * *'  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Fetch data
      run: |
        # Replace this with the command you use to fetch data
        date "+%Y-%m-%d %H:%M:%S" >> data.txt

    - name: Commit and push if it changed
      run: |
        git config --global user.email "RonggolawePutri577@gmail.com"
        git config --global user.name "Putri577"
        git add -A
        git diff --quiet && git diff --staged --quiet || git commit -m "Updated data"
        git push
